// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package nats

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "nats", asset.ModuleFieldsPri, Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJzUmb+S2zYQxvt7ih1XSWE9gIrMZJLGRVzknFqGwBWFmMDSi4XOuqfPABQligIpSkffXVRccaD2+/ED8OGPPsI33C/BKfEPAGKkwiV8+KzEf3gAKNBrNrUYckv47QEA0pPwFxWhwgeAjcGq8MvU8hGcsnisFT+yr3EJJVOoD//JVIyfr/FLX0GTE2WcBy9KjBejPchWCTwhIzCqAjZMFj6fJLoEXQqPvENemOLY0uJ8w/0Tcff/A1Dx82WLh1Lw6c8hETEWL2QKJThN47GpH6sAbcCisNGgGVV8+kJUk3OoY5O/EO1afUX1j9br1KOnosBYKcHiwNHV6HvdpRISVZ21tEzGCZbIvbYRstZ3F+waOVqiAzM6qfagtJgdgq4MOvEX3jAFwRltSfXeoyOMpfGCjEX/nY9jU5TM6MRO8Z0+hLo3P040FbnydhdqZEMFyGlqGg+hhl886l+zCBbtYr0/HxmjFBtiq2QJuS9NIDyM16hLvIfgVZmm9uffvzxCzaTR+yyoJh6AnGHMVFQarapGJNnX5QEOzkMnb8646pCl8lpVWKw2FSkZsLBG1uj6rTeYqOtw5qAfdTDNulU+I+GFA+9kZVKp9k1IY3GRR10iRktDQ2/mJMgotRTGZQH6eTBRXlkKTqK8cZqscWVc71R/CGRSAc6mpY/92rcGxrppAuAI5KBii5Sb8Fd5xtLiZbyXFVtQCv0pNVOHUpCS3nuHHiH/Jx165B3uUF/RU8wtHyzyz0mtKAFHic6uilxaCrJcW5F6xfh9lTYUCyaSVWCTBaT1v6hvjPoe49ZIXIUg6oAlZ4Q4GteXHMCLwf88K18eL+ncwZc2a68B2AjdQejD2r8GYNK5hy/+fQ2+qDOVb84ojvXaLfZx09hsdG+M46Npg/mXQ5yA2aIyfg/opXtez6XpAGYX9bI/p4FOhO0BQ2G8sFmHdOAl1+3mf/7+9DhQY+xFoH8KfR587Mric+NrwQsiIAefku3N2a/maw59p/jtySPEreApC9+c/Goi59DjOv3m5GObha7HrcqM9yJnZd/jTdHhxmzo9bsnRI98sVbMs/NsagPVyKpxyriedZXxMnh+3k2/urnx8Bxr38dllejtT+ISY9GDajTAeNhQcEU8l4A648vf1ii9xYU3z/lbt1kuHXyoBDxKcky22IiO4GyNrPj8Thxe5R4piradBYoR1hgzguMUxR0eflK4hr9RjoIsrPoxr6dW/TA2WGjqN/u8Atb7qUBq1x9oh58fKKyrvtlTLgJ2yKrEIZ7/AgAA//8lib+8"
}
